---
  # file: apicontroller.yml
  # This playbook deploy registries apicontroller

- name: Install web service
  hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: apt update && apt-get -y install python
      tags: ["install"]

- name: Install web service
  hosts: [web]
  roles:
  - { role: web, tags: ["web"] }